# Generated by Django 4.0.4 on 2022-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategroyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('ToolId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolName', models.CharField(max_length=100)),
                ('ToolNotes', models.CharField(max_length=1000)),
                ('ToolLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('TypeId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
            ],
        ),
    ]
