# Generated by Django 3.2.10 on 2022-04-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='CategroyName',
            new_name='CategoryName',
        ),
    ]
