# Generated by Django 3.2.10 on 2022-05-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0003_tool_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('CommandId', models.AutoField(primary_key=True, serialize=False)),
                ('Command', models.CharField(max_length=100)),
                ('CommandNotes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='Commands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securityApp.command'),
        ),
    ]
