# Generated by Django 3.2.10 on 2022-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0004_auto_20220502_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='Command',
            new_name='CommandName',
        ),
    ]
