# Generated by Django 3.2.10 on 2022-05-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0005_rename_command_command_commandname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='Commands',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
