# Generated by Django 3.2.10 on 2022-05-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0007_auto_20220502_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommandText', models.CharField(max_length=100)),
                ('CommandNotes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='Commands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securityApp.commandlist'),
        ),
    ]
