# Generated by Django 3.2.10 on 2022-05-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securityApp', '0009_auto_20220502_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='Commands',
        ),
        migrations.AddField(
            model_name='command',
            name='ToolKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securityApp.tool'),
        ),
    ]
